---
# tasks file for roles/database
- name: Run DATABASE
  docker_container:
    name: database
    image: youreastonefox/tp3-database:latest
    pull: true
    env:
      POSTGRES_PASSWORD: "{{postgres_pwd}}"
    networks:
      - name: "{{ docker_network }}"
