version: "3.7"

services:
  backend:
    build: /api/simple-api-student-main/
    container_name: api
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: /database/
    container_name: database
    volumes:
      - db-data
    environment:
      - POSTGRES_PASSWORD=pwd
    networks:
      - app-network

  httpd:
    build: /http/
    container_name: httpd
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  front:
    build: /front/
    container_name: front
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:

volumes:
  db-data:
