---
# tasks file for roles/httpd
- name: Run HTTPD
  docker_container:
    name: httpd
    image: youreastonefox/tp3-httpd:latest
    pull: true
    ports:
      - "80:80"
    networks:
      - name: "{{ docker_network }}"
