name: CI MAIN

on:
  workflow_run:
    workflows: [CI DEV]
    types: [completed]
    branches: [tp3]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PWD }}"

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp3-api
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/tp3' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp3-database
          push: ${{ github.ref == 'refs/heads/tp3' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp3-httpd
          push: ${{ github.ref == 'refs/heads/tp3' }}
