name: CI EXTRAS

on:
  push:
    branches:
      - "extra"

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: corretto # Distribution obligatoire, choix de celle utilisée dans l'API
          java-version: "17" # Utilisation JDK 17

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Youreastonefox_s8-devops -Dsonar.organization=module-devops-4irc -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./api/pom.xml

  # define job to build and publish docker image
  build-and-push-docker-image:
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PWD }}"

      - name: Build image and push backend 1
        uses: docker/build-push-action@v3
        with:
          context: ./backend-1
          tags: ${{secrets.DOCKERHUB_USERNAME}}/extra-backend-1
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push backend 2
        uses: docker/build-push-action@v3
        with:
          context: ./backend-2
          tags: ${{secrets.DOCKERHUB_USERNAME}}/extra-backend-2
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/extra-database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http
          tags: ${{secrets.DOCKERHUB_USERNAME}}/extra-httpd
          push: ${{ github.ref == 'refs/heads/main' }}
